routes/web.php
<?php

/*
|---------------------------------------------------------------------		-----
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/logout', 'Auth\LoginController@logout')->name('logout.get');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function() {
    Route::get('/', 'DashboardController@index')->name('homepage');

    Route::get('banners/trashed', 'BannerController@trashed')->name('banners.trashed');
    Route::post('banners/{id}/restore', 'BannerController@restore')->name('banners.restore');
    Route::resource('banners', 'BannerController');

    Route::get('banner-groups/trashed', 'BannerGroupController@trashed')->name('banner-groups.trashed');
    Route::post('banner-groups/{id}/restore', 'BannerGroupController@restore')->name('banner-groups.restore');
	Route::resource('banner-groups', 'BannerGroupController');

	Route::post('banners-save-order/{group_id}', ['as' => 'save-banners-order', 
												  'uses' =>'BannerGroupBannerController@saveBannersOrder']);

	Route::post('banner-save-data/{group_id}', ['as' => 'save-banner-data', 
												  'uses' =>'BannerGroupBannerController@saveBannerData']);

    Route::post('users/key/generate', 'UserController@generateKey')->name('users.generate_key');
    Route::get('users/{id}/delete', 'UserController@destroy')->name('users.delete');
	Route::resource('users', 'UserController');
});

app/Models/Banner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Banner extends Model
{
    use SoftDeletes;

    protected $fillable = ['name', 'image', 'url',  'user_id'];
    protected $dates =  ['deleted_at'];
    public function bannerGroups() {
    	return $this->belongsToMany('App\Models\BannerGroup', 'banner_group_banner')->withPivot('time','show_till','order');
  	}

}

app/Http/Controllers/BannerController.php
<?php

namespace App\Http\Controllers;

use Image;
use Illuminate\Http\Request;
use App\Models\Banner;
use App\Models\BannerGroup;
use function MongoDB\BSON\toJSON;


class BannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.banner.list', [
            'banners' => Banner::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.banner.form', [
            'banner' => new Banner(),
            'bannerGroups' => BannerGroup::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('pages.banner.form', [
            'banner' => Banner::find($id),
            'bannerGroups' => BannerGroup::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if($id == 0){
            $banner = new Banner ();
        } else {
            $banner = Banner::find($id);
        }
        $banner->fill($request->all());
        $banner->save();

        if (isset($request->groups)) {
            $banner->bannerGroups()->sync($request->groups);
        }

        if($request->image) {
            $image = Image::make($request->image);
            unlink($request->image);
            $filepath = 'banners_images/banner_'.$banner->id.'.jpg';
            $image->interlace()->save($filepath);
            $banner->image = $filepath;
        }
       
        $banner->save();

        return redirect(route('banners.edit', $banner->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $banner = Banner::withTrashed()->where('id', $id)->first();
        if (!$banner->trashed()) {
            $banner->delete();
        } else {
            unlink('../public/' . $banner->image);
            $banner->forceDelete();

        }

    }

    /**
     * Display a listing of the deleted banners
     *
     * @return \Illuminate\Http\Response
     */
    public function trashed()
    {
        return view('pages.banner.list', [
            'banners' => Banner::onlyTrashed()->get()]);
    }

    /**
     * Restore deleted banner.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        $banner = Banner::withTrashed()->where('id', $id)->first();
        $banner->restore();
    }
}

resources/views/pages/banner/form.blade.php
@extends('common.index')

@section('styles')

@endsection

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                @if($banner->id)
                    {{$banner->name}}
                @else
                    Создание баннера
                @endif
            </h1>
            <ol class="breadcrumb">
                <li><a href="/"><i class="fa fa-dashboard"></i> Панель управления</a></li>
                <li><a href="{{route('banners.index')}}">Список баннеров</a></li>
                @if($banner->id)
                    <li class="active">{{$banner->name}}</li>
                @else
                    <li class="active">Создание</li>
                @endif
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <!-- <div class="box-header">
                        </div> -->
                        <div class="box-body">
                            <!-- Date -->
                            <form class="col-md-6" action="{{route('banners.update', $banner->id? $banner->id:0)}}"
                                  method="POST" enctype="multipart/form-data">

                                <div class="form-group">
                                    <label for="bannerName">Hазвание баннера</label>
                                    <input type="text" class="form-control" id="bannerName" name="name"
                                           value="{{$banner->name}}" required>
                                </div>

                                <div class="form-group">
                                    <label for="bannerUrl">Ссылка баннера</label>
                                    <input type="text" class="form-control" id="bannerUrl" name="url"
                                           value="{{$banner->url}}" required>
                                </div>

                                <div class="form-group">
                                    <label>Группы баннеров</label>
                                    <select class="form-control" multiple name="groups[]">
                                        @foreach($bannerGroups as $group)
                                            <option value="{{$group->id}}"
                                                    @if($banner->bannerGroups->contains($group->id))
                                                    selected
                                                    @endif>

                                                {{$group->name}}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Загрузить баннер</label>
                                    <input type="file" class="form-control" class="btn btn-primary" name="image"
                                    @if(empty($banner->image))
                                           required
                                    @endif>
                                </div>

                                {{csrf_field()}}
                                <input type="hidden" name="user_id" value="{{Auth::user()->id}}">
                                <input type="hidden" name="_method" value="PUT">
                                <input type="hidden" name="id" value="{{$banner->id}}">
                                <input type="submit" class="btn btn-primary" value="Сохранить">
                            </form>

                            <div class="col-md-6">
                                @if($banner->image)
                                    <img src="/{{$banner->image}}" style="max-height: 304px;margin: 0 auto;">
                                @else
                                    <img src="https://s9.stc.all.kpcdn.net/share/i/12/10065254/inx960x640.jpg"
                                         style="max-height: 304px;margin: 0 auto;">
                                @endif
                            </div>

                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.row -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@section('scripts')
@endsection

resources/views/pages/banner/list.blade.php
@extends('common.index')

@section('styles')
    <!-- DataTables -->
    <link rel="stylesheet" href="../../bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@endsection

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Список баннеров
                @if(Route::currentRouteName() == 'banners.trashed')
                    <a href="{{route('banners.index')}}">
                        <small>Корзина</small>
                    </a>
                @else
                    <a href="{{route('banners.trashed')}}">
                        <small>Все</small>
                    </a>
                @endif
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Панель управления</a></li>
                @if(Route::currentRouteName() != 'banners.trashed')
                    <li class="active">Список баннеров</li>
                @else
                    <li><a href="{{route('banners.index')}}">Список баннеров</a></li>
                    <li class="active">Корзина</li>
                @endif
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <!--  <div class="box-header">
                        </div> -->
                        <!-- /.box-header -->
                        <div class="box-body">
                            <input type="hidden" class="token" value="{{csrf_token()}}">
                            <table id="main-table" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Миниатюра</th>
                                    <th>Название</th>
                                    <th>Группа баннеров</th>
                                    <th>Управление</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($banners as $banner)
                                    <tr data-id="{{$banner->id}}">
                                        <td>{{$banner->id}}</td>
                                        <td>
                                            @if($banner->image)
                                                <img class="banner-miniature img-responsive img-square"
                                                     src="/{{$banner->image}}" alt="Изображение баннера">

                                            @else
                                                <img class="banner-miniature img-responsive img-square"
                                                     src="/img/boxed-bg.jpg" alt="У баннера нет изображения">

                                            @endif
                                        </td>
                                        <td>{{$banner->name}}</td>
                                        <td>
                                            @if($banner->bannerGroups())
                                                @foreach($banner->bannerGroups()->get() as $group)
                                                    <a href="{{route('banner-groups.edit', $group->id)}}"
                                                       target="_blank">{{$group->name}} </a>  @if(!$loop->last) | @endif
                                                @endforeach
                                            @else
                                                Без групп
                                            @endif
                                        </td>
                                        <td>
                                            <a class="btn btn-warning btn-edit" title="Редактировать"
                                               href="{{route('banners.edit', $banner->id)}}"><i
                                                        class="fa fa-pencil" aria-hidden="true"></i></a>
                                            @if(Route::currentRouteName() == 'banners.trashed')
                                            <button class="btn btn-success btn-restore" data-id="{{$banner->id}}"><i
                                                        class="fa fa-level-up"
                                                        aria-hidden="true" title="Восстановить"></i></button>
                                            @endif
                                            <button class="btn btn-danger btn-delete" data-id="{{$banner->id}}"><i
                                                        class="fa fa-trash"
                                                        aria-hidden="true" title="Удалить"></i>
                                            </button>

                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Миниатюра</th>
                                    <th>Название</th>
                                    <th>Группа баннеров</th>
                                    <th>Управление</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('modals')
    <div class="modal modal-danger fade" id="modal-delete">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Удаление баннера</h4>
                </div>
                <div class="modal-body">
                    @if(Route::currentRouteName() == 'banners.trashed')
                    <p>Вы действительно хотите удалить баннер? Изображение так же будет удалено.</p>
                    @else
                    <p>Вы действительно хотите убрать баннер в корзину?</p>
                    @endif
                    <input type="hidden" class="delete-banner-id">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Закрыть</button>
                    <button type="button" class="btn btn-outline btn-remove">Убрать</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    <div class="modal modal-success fade" id="modal-restore">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Восстановление баннера</h4>
                </div>
                <div class="modal-body">
                        <p>Вы действительно хотите восстановить баннер?</p>
                    <input type="hidden" class="restore-banner-id">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Закрыть</button>
                    <button type="button" class="btn btn-outline btn-restore-banner">Восстановить</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
@endsection

@section('scripts')
    <!-- DataTables -->
    <script src="/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <!-- page script -->
    <script>


        $(".btn-delete").click(function () {
            $('.delete-banner-id').val($(this).data('id'));
            $('#modal-delete').modal('show');
        });

        $(".btn-remove").click(function () {
            var id = $('.delete-banner-id').val();
            var sendAr = {
                _method: 'DELETE',
                _token: $('.token').val()
            };
            $.post('/banners/' + id, sendAr, function (data) {
                console.log(data);
                $('tr[data-id="' + id + '"]').fadeOut(600);
            });
            $('#modal-delete').modal('hide');
        });

        @if(Route::currentRouteName() == 'banners.trashed')
        $(".btn-restore").click(function () {
            $('.restore-banner-id').val($(this).data('id'));
            $('#modal-restore').modal('show');
        });

        $(".btn-restore-banner").click(function () {
            var id = $('.restore-banner-id').val();
            var sendAr = {
                _token: $('.token').val()
            };
            $.post('/banners/' + id + '/restore', sendAr, function (data) {
                $('tr[data-id="' + id + '"]').fadeOut(600);
            });
            $('#modal-restore').modal('hide');
        });
        @endif

        $(function () {
            $('#main-table').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': true,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
    </script>
@endsection