routes/web.php
<?php

/*
|---------------------------------------------------------------------		-----
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/logout', 'Auth\LoginController@logout')->name('logout.get');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function() {
    Route::get('/', 'DashboardController@index')->name('homepage');

    Route::get('banners/trashed', 'BannerController@trashed')->name('banners.trashed');
    Route::post('banners/{id}/restore', 'BannerController@restore')->name('banners.restore');
    Route::resource('banners', 'BannerController');

    Route::get('banner-groups/trashed', 'BannerGroupController@trashed')->name('banner-groups.trashed');
    Route::post('banner-groups/{id}/restore', 'BannerGroupController@restore')->name('banner-groups.restore');
	Route::resource('banner-groups', 'BannerGroupController');

	Route::post('banners-save-order/{group_id}', ['as' => 'save-banners-order', 
												  'uses' =>'BannerGroupBannerController@saveBannersOrder']);

	Route::post('banner-save-data/{group_id}', ['as' => 'save-banner-data', 
												  'uses' =>'BannerGroupBannerController@saveBannerData']);

    Route::post('users/key/generate', 'UserController@generateKey')->name('users.generate_key');
    Route::get('users/{id}/delete', 'UserController@destroy')->name('users.delete');
	Route::resource('users', 'UserController');
});

app/Models/BannerGroup.php
<?php

namespace App\Models;

use Date;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class BannerGroup extends Model
{
    use SoftDeletes;

    protected $fillable = ['name', 'user_id'];
    protected $dates =  ['deleted_at'];

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }
    public function banners()
    {
        return $this->belongsToMany('App\Models\Banner', 'banner_group_banner')->withPivot('time', 'show_till', 'order');
    }

    public function api_banners()
    {
        return $this->belongsToMany('App\Models\Banner', 'banner_group_banner')
            ->withPivot('time', 'show_till', 'order')
            ->where('banner_group_banner.show_till', null)
            ->orWhere('banner_group_banner.show_till', '>', Date::now())
            ->orderBy('banner_group_banner.order', 'asc');
    }

}

app/Http/Controllers/BannerGroupController.php
<?php

namespace App\Http\Controllers;

use App\Models\Banner;
use App\Models\BannerGroup;
use Illuminate\Http\Request;

class BannerGroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.banner_group.list', [
            'groups' => BannerGroup::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.banner_group.form', [
            'group' => new BannerGroup(),
            'banners' => Banner::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         return view('pages.banner_group.form', [
            'group' => BannerGroup::find($id),
            'banners' => Banner::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if($id == 0){
            $group = new BannerGroup();
        } else {
            $group = BannerGroup::find($id);
        }
        $group->fill($request->all());

        $group->save();

        return redirect(route('banner-groups.edit', $group->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $group = BannerGroup::withTrashed()->where('id', $id)->first();
        if (!$group->trashed()) {
            $group->delete();
        } else {
            $group->forceDelete();

        }
    }

    /**
     * Display a listing of the deleted banners
     *
     * @return \Illuminate\Http\Response
     */
    public function trashed()
    {
        return view('pages.banner_group.list', [
            'groups' => BannerGroup::onlyTrashed()->get()]);
    }

    /**
     * Restore deleted banner.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        $group = BannerGroup::withTrashed()->where('id', $id)->first();
        $group->restore();
    }

}

resources/views/pages/banner_group/form.blade.php
@extends('common.index')

@section('styles')
    <link rel="stylesheet" href="/bower_components/bootstrap-datetimepicker/bootstrap-datetimepicker.min.css">
@endsection

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                @if($group->id)
                    {{$group->name}}
                @else
                    Создание группы
                @endif
            </h1>
            <ol class="breadcrumb">
                <li><a href="/"><i class="fa fa-dashboard"></i> Панель управления</a></li>
                <li><a href="{{route('banner-groups.index')}}">Список групп баннеров</a></li>
                @if($group->id)
                    <li class="active">{{$group->name}}</li>
                @else
                    <li class="active">Создание</li>
                @endif
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <div class="row">
                <div class="col-md-12">
                    <div class="box box-primary">
                        <!-- <div class="box-header">
                        </div> -->
                        <div class="box-body">
                            <!-- Date -->
                            <form class="col-md-12" action="{{route('banner-groups.update', $group->id? $group->id:0)}}"
                                  method="POST" enctype="multipart/form-data" name="group-editor" id="group-editor">

                                <div class="form-group col-md-6 col-xs-12">
                                    <label for="bannerName">Hазвание группы</label>
                                    <input type="text" class="form-control" id="bannerName" name="name"
                                           value="{{$group->name}}" required>
                                </div>
                                <div class="col-md-6 col-xs-12">
                                    <br>
                                    <p class="text-light-blue">
                                        <i class="fa fa-info-circle" aria-hidden="true"></i>
                                        На данный момент, баннеры добавляются в группу при их редактировании</p>
                                </div>
                                {{csrf_field()}}
                                <input type="hidden" name="user_id" value="{{Auth::user()->id}}">
                                <input type="hidden" name="_method" value="PUT">
                                {{--<input type="hidden" name="id" value="{{$group->id}}">--}}
                                @if(!empty($group->id))
                                <table id="main-table" class="table table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>Название</th>
                                        <th>Время показа (сек.)</th>
                                        <th>Отображать до</th>
                                    </tr>
                                    </thead>
                                    <tbody class="bannerRows">
                                    @foreach($group->banners()->orderBy('pivot_order', 'asc')->get() as $banner)
                                        <tr class="bannerRow" data-id="{{$banner->id}}">
                                            <td>
                                                {{$banner->name}}
                                            </td>
                                            <td>
                                                <input class="form-control time" type="number" min="1" max="100"
                                                       value="{{$banner->pivot->time}}">
                                            </td>
                                            <td>
                                                <div class="input-group date">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-calendar"></i>
                                                    </div>
                                                    <input type="text" class="form-control pull-right show_till"
                                                           value="{{$banner->pivot->show_till}}">
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th>Название</th>
                                        <th>Время показа (сек.)</th>
                                        <th>Отображать до</th>
                                    </tr>
                                    </tfoot>
                                </table>
                                @endif
                            </form>
                            <input type="submit" class="btn btn-primary" value="Сохранить" form="group-editor">
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box -->
                    </div>
                    <!-- /.row -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@section('scripts')
    <script src="/bower_components/moment/min/moment.min.js"></script>

    <script src="/bower_components/bootstrap-datetimepicker/bootstrap-datetimepicker.min.js"></script>


    <script type="text/javascript">
        $(".bannerRows").sortable({
            stop: function () {
                var bannersOrder = [];
                $('.bannerRow').each(function () {
                    bannersOrder.push($(this).attr('data-id'));
                });

                bannersOrder.pop();
                $.post('{{ route('save-banners-order', $group->id) }}', {
                    bannersOrder: bannersOrder,
                    _token: '{{ csrf_token() }}'
                }, 'json');
            }
        });
        $(".bannerRow").change(function () {
            var sendAr = {
                _token: '{{ csrf_token() }}',
                id: $(this).attr('data-id'),
                time: $(this).find('.time').val(),
                show_till: $(this).find('.show_till').val()
            };

            $.post('{{ route('save-banner-data', $group->id) }}',
                sendAr, 'json');
        });

        //Date picker
        $('.date').datetimepicker({
            format: "Y-MM-DD HH:mm:ss"
        })

        $(".date").on("dp.change", function(e) {
            $(this).closest('.bannerRow').trigger('change');
        });

    </script>
@endsection

resources/views/pages/banner_group/list.blade.php
@extends('common.index')

@section('styles')
    <!-- DataTables -->
    <link rel="stylesheet" href="../../bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@endsection

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Список групп
                @if(Route::currentRouteName() == 'banner-groups.trashed')
                    <a href="{{route('banner-groups.index')}}">
                        <small>Корзина</small>
                    </a>
                @else
                    <a href="{{route('banner-groups.trashed')}}">
                        <small>Все</small>
                    </a>
                @endif
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Панель управления</a></li>
                @if(Route::currentRouteName() != 'banner-groups.trashed')
                    <li class="active">Список групп</li>
                @else
                    <li><a href="{{route('banner-groups.index')}}">Список групп</a></li>
                    <li class="active">Корзина</li>
                @endif
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <!--  <div class="box-header">
                        </div> -->
                        <!-- /.box-header -->
                        <div class="box-body">
                            <input type="hidden" class="token" value="{{csrf_token()}}">
                            <table id="main-table" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Название</th>
                                    <th>Включенные баннеры</th>
                                    <th>Управление</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($groups as $group)
                                    <tr data-id="{{$group->id}}">
                                        <td>{{$group->id}}</td>

                                        <td>{{$group->name}}</td>
                                        <td>
                                            @if($group->banners())
                                                @foreach($group->banners()->get() as $banner)
                                                    <a href="{{route('banners.edit', $banner->id)}}"
                                                       target="_blank">{{$banner->name}} </a> @if(!$loop->last) | @endif
                                                @endforeach
                                            @else
                                                Без баннеров
                                            @endif
                                        </td>
                                        <td>
                                            <a class="btn btn-warning btn-edit" title="Редактировать"
                                               href="{{route('banner-groups.edit', $group->id)}}"><i
                                                        class="fa fa-pencil" aria-hidden="true"></i></a>
                                            @if(Route::currentRouteName() == 'banner-groups.trashed')
                                                <button class="btn btn-success btn-restore" data-id="{{$group->id}}"><i
                                                            class="fa fa-level-up"
                                                            aria-hidden="true" title="Восстановить"></i></button>
                                            @endif
                                            <button class="btn btn-danger btn-delete" data-id="{{$group->id}}"><i
                                                        class="fa fa-trash"
                                                        aria-hidden="true" title="Удалить"></i>
                                            </button>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Название</th>
                                    <th>Включенные баннеры</th>
                                    <th>Управление</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('modals')
    <div class="modal modal-danger fade" id="modal-delete">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Удаление группы</h4>
                </div>
                <div class="modal-body">
                    @if(Route::currentRouteName() == 'banner-groups.trashed')
                        <p>Вы действительно хотите удалить группу? Баннеры группы удалены не будут.</p>
                    @else
                        <p>Вы действительно хотите убрать группу в корзину?</p>
                    @endif
                    <input type="hidden" class="delete-group-id">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Закрыть</button>
                    <button type="button" class="btn btn-outline btn-remove">Убрать</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    <div class="modal modal-success fade" id="modal-restore">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Восстановление группы</h4>
                </div>
                <div class="modal-body">
                    <p>Вы действительно хотите восстановить группу?</p>
                    <input type="hidden" class="restore-group-id">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Закрыть</button>
                    <button type="button" class="btn btn-outline btn-restore-group">Восстановить</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
@endsection

@section('scripts')
    <!-- DataTables -->
    <script src="/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <!-- page script -->
    <script>

        $(".btn-delete").click(function () {
            $('.delete-group-id').val($(this).data('id'));
            $('#modal-delete').modal('show');
        });

        $(".btn-remove").click(function () {
            var id = $('.delete-group-id').val();
            var sendAr = {
                _method: 'DELETE',
                _token: $('.token').val()
            };
            $.post('/banner-groups/' + id, sendAr, function (data) {
                console.log(data);
                $('tr[data-id="' + id + '"]').fadeOut(600);
            });
            $('#modal-delete').modal('hide');
        });

        @if(Route::currentRouteName() == 'banner-groups.trashed')
        $(".btn-restore").click(function () {
            $('.restore-group-id').val($(this).data('id'));
            $('#modal-restore').modal('show');
        });

        $(".btn-restore-group").click(function () {
            var id = $('.restore-group-id').val();
            var sendAr = {
                _token: $('.token').val()
            };
            $.post('/banner-groups/' + id + '/restore', sendAr, function (data) {
                $('tr[data-id="' + id + '"]').fadeOut(600);
            });
            $('#modal-restore').modal('hide');
        });
        @endif

        $(function () {
            $('#main-table').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': true,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
    </script>
@endsection